package com.rishabh.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@DynamoDBTable(tableName = "ProductInfo")
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class ProductInfo {

    public ProductInfo(String msrp, String cost, Long order) {
        this.msrp = msrp;
        this.cost = cost;
        this.order = order;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey(attributeName = "order") // Sort key
    private Long order;

    @DynamoDBAttribute
    private String msrp;

    @DynamoDBAttribute
    private String cost;
}
